### ISSUE TITLE
about component

### ISSUE THREAD

**Issue by penguin3069** [kadira-samples/redux-routing-example#2]
Thanks for your sharing.I noticed there are two files in each component directory--'component.js' and 'container.js'.component.js is in charge of UI,and container.js manages data with redux.Does it mean react-component should be pure,so we can reuse the component easily?

My English is not very well,can you understand what I say?

**Comment by arunoda** [comment]
Component should not be **pure**. It should not contain anything related to Redux.

**Comment by penguin3069** [comment]
Thanks.
