### ISSUE TITLE
Do not subscribe here*

### ISSUE THREAD

**Issue by rclai** [kadira-samples/redux-routing-example#3]
There is no need to do this here:

https://github.com/kadira-samples/rethinking-redux-demo/blob/93cb4c7516f854e6eca13ec618cd746f7a1c4bfc/src/index.js#L26-L34

Doesn't it give you errors? Or warnings?

Using `connect` from `react-redux` to subscribe to the store in a fine-grained manner should be enough.

**Comment by arunoda** [comment]
No it won't throw any error because it's React :) 
It just some old code.
I'll remove it.

**Comment by rclai** [comment]
Oh okay cool.
